//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKinoStudio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinoStudioEntities2 : DbContext
    {
        public KinoStudioEntities2()
            : base("name=KinoStudioEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actors> Actors { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Presidents> Presidents { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Studios> Studios { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
